CREATE TABLE `movie_master` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) DEFAULT NULL,
  `CATEGORY` varchar(150) DEFAULT NULL,
  `RATING` double DEFAULT '0.5',
  `IS_DELETED` bit(1) DEFAULT b'0',
  `CREATED_ON` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
